# Generated by Django 5.1.5 on 2025-05-25 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_varified_customuser_otp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
